### ISSUE TITLE
Inspect the database for missing disks

### ISSUE THREAD

**Issue by cholcombe973** [Comcast/Bynar#42]
Linux has an issue where if a disk fails it often gets removed from the file tree.  That makes it impossible to know if the disk doesn't exist or it just failed unless we previously recorded it somewhere.  The goal of this task is to modify the `check_all_disks` fn in the test_disk.rs file and have it communicate with the database to check if there's any missing disks.  If they are missing can we assume they are failed and need intervention?

**Comment by sdandam** [comment]
add_previous_devices() has been implemented as part of another issue. https://github.com/Comcast/Bynar/pull/50/
